title: My Blog
author: Meghavi Patel
description: A blog about full stack development and other cool stuff.
url: "https://github.com/Meghavi-Patel/meghavi-patel.github.io"

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
