title: My Blog
author: Meghavi Patel
description: A blog about full stack development and other cool stuff.
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
